[package]
name = "notesman"
version = "0.5.3"
authors = ["robert arles <robert@arles.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2.33"
